config/routes.rb
BackboneTodoApp::Application.routes.draw do

  get "top/index"
  resources :todos do
    member do
      get 'filter' => 'todos#index'
    end
  end

  resources :marionette_todos do
    member do
      get 'filter' => 'marionette_todos#index'
    end
  end

   root 'top#index'

end

app/models/todo.rb
class Todo < ActiveRecord::Base
  DONE = 1
  PENDING = 0
  validates :item, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/marionette_todos_controller.rb
class MarionetteTodosController < TodosController
  before_action :render_404


private
  def render_404
    render file: 'public/404.html', status: 404, layout: nil
  end

  def todo_params
    params.require(:marionette_todo).permit(:status, :item)
  end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :set_todo, only: [:show, :update, :destroy]
  before_action :todo_list, only: [:index, :new, :edit]

  # GET /todos
  # GET /todos.json
  def index
  end

  # GET /todos/1
  # GET /todos/1.json
  def show
  end

  # GET /todos/new
  def new
    render action: :index
  end

  # GET /todos/1/edit
  def edit
    render action: :index
  end

  # POST /todos
  # POST /todos.json
  def create
    @todo = Todo.new(todo_params)

    respond_to do |format|
      if @todo.save
        format.html { redirect_to @todo, notice: 'Todo was successfully created.' }
        format.json { render action: 'show', status: :created, location: @todo }
      else
        format.html { render action: 'new' }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todos/1
  # PATCH/PUT /todos/1.json
  def update
    respond_to do |format|
      if @todo.update(todo_params)
        format.html { redirect_to @todo, notice: 'Todo was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todos/1
  # DELETE /todos/1.json
  def destroy
    @todo.destroy
    respond_to do |format|
      format.html { redirect_to todos_url }
      format.json { head :no_content }
    end
  end

  private
    def todo_list
      @todos = Todo.all
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_todo
      @todo = Todo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def todo_params
      params.require(:todo).permit(:status, :item)
    end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/marionette_todos_helper.rb
module MarionetteTodosHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "BackboneTodoApp" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->
    <link href="http://fonts.googleapis.com/css?family=Merienda+One" rel="stylesheet" type="text/css">
    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-fluid-top">

      <div id="header" class="jumbotron masthead">
        <div class="container">
          <h1>BackboneTodoApp</h1>
        </div>
      </div>

    </div>

    <div class="container-fluid">
      <div id="wrapper" class="row-fluid">
        <!--<div class="span3">
          <div class="well sidebar-nav">
            <ul class="nav nav-list">
              <li class="nav-header">Sidebar</li>
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div>/.well -->
        </div><!--/span-->
        <div id="main" class="span12">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->
      <div class="push"></div>
      <footer id="footer">
        <span id="github_and_company">
          <span id="github" class="pull-left">
            <i class="icon-github icon-2x"></i>
            <a style="color:white;" href="https://github.com/gaiax-asia/backbone_todo_app"> Fork me on Github</a><br/>
          </span>
          <span id="company" class="pull-right"><p>&copy; GaiaX Asia Corporation 2013</p></span>
        </span>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/marionette_todos/index.html.erb
<%= javascript_include_tag "marionette_init.js"%>
<%= javascript_include_tag "marionette_todos.js"%>

<script type="text/javascript">
  $(function(){
    MarionetteTodosApp.currentRouter = new MarionetteTodosApp.Routers.Todos(<%= @todos.to_json.html_safe %>);
  });
</script>

<%= render partial: '/templates/todo_index'%>
<%= render partial: '/templates/todo_item'%>

app/views/templates/_todo_index.html.erb
<script type="text/template" id="todo_index">
  <div class="notebook" >
    <div class="body">
    <h4>
      Todos
      <span id="filters" class="pull-right">
        <i id="reset" title="Refresh List" class="icon-refresh"></i>
        <i id="filter-done" title="Filter Done" class="icon-ok"></i>
        <i id="filter-pending" title="Filter Pending" class="icon-time"></i>
      </span>
    </h4>
      <ul class="list">
        <li id="add-todo">
          <div class="lines"></div>
          <span id="todo-display-add">
            add new todo
          </span>
          <span id="todo-addable" style="display:none" >
            <input class="todo-item-input" id="add-todo-value" type="text">
            <i id="hide-add-todo" title="Cancel" class="icon-remove"></i>
          </span>
          <span class="pull-right">
            <i title="Add New Todo" class="icon-plus"></i>
          </span>
        </li>
      </ul>
    </div>
  </div>
</script>

app/views/templates/_todo_item.html.erb
<script type="text/template" id="todo_item">
  <div class="lines"></div>
  <span>
    <i id="todo-checkbox" style="text-indent: -10px" title="Check Todo" class="icon-check{%todo.status == <%= Todo::PENDING %> ?'-empty' : '' %}"></i>
    <span id="todo-display-edit" class="{% todo.status == <%= Todo::DONE %> ? 'checked' : '' %}">
      {%todo.item%}
    </span>
    <span id="todo-editable" style="display:none" >
      <input class="todo-item-input" id="edit-todo-value" value="{%todo.item%}" type="text">
      <i title="Cancel Edit" class="icon-remove"></i>
    </span>
  </span>
  <span class="pull-right">
    <i id="edit-todo" title="Edit Todo" class="icon-edit"></i>
    <i id="remove-todo" title="Remove Todo" class="icon-trash"></i>
  </span>
</script>

app/views/todos/_form.html.erb
<%= form_for(@todo) do |f| %>
  <% if @todo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@todo.errors.count, "error") %> prohibited this todo from being saved:</h2>

      <ul>
      <% @todo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :status %><br>
    <%= f.number_field :status %>
  </div>
  <div class="field">
    <%= f.label :item %><br>
    <%= f.text_field :item %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/todos/edit.html.erb
<h1>Editing todo</h1>

<%= render 'form' %>

<%= link_to 'Show', @todo %> |
<%= link_to 'Back', todos_path %>

app/views/todos/index.html.erb
<%= javascript_include_tag "init.js"%>
<%= javascript_include_tag "todos.js"%>

<script type="text/javascript">
  $(function(){
    TodosApp.currentRouter = new TodosApp.Routers.Todos(<%= @todos.to_json.html_safe %>);
  });
</script>

<%= render partial: '/templates/todo_index'%>
<%= render partial: '/templates/todo_item'%>

app/views/todos/new.html.erb
<h1>New todo</h1>

<%= render 'form' %>

<%= link_to 'Back', todos_path %>

app/views/todos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Status:</strong>
  <%= @todo.status %>
</p>

<p>
  <strong>Item:</strong>
  <%= @todo.item %>
</p>

<%= link_to 'Edit', edit_todo_path(@todo) %> |
<%= link_to 'Back', todos_path %>

app/views/top/index.html.erb
<h1 class="text" >Select what the TodoApp is made of.</h1>
<div class="push"></div>
<div class="container-fluid">

  <%= image_tag "backbone.png", class: 'span6 shake',
                                id: 'bbapp',
                                title: 'The app is made with Backbone and plain Javascript',
                                style: 'height:10em;width:30%;'  %>
  <%= image_tag "marionette.png", class: 'span6 shake',
                                id: 'bbmapp',
                                title: 'The app is made with Backbone wrapped in Marionette and Coffeescript',
                                style: 'height:17em;width:30%;padding-left:30%;'  %>
</div>


<script type="text/javascript">
$(function(){
  $('#bbapp').on('click',function(e){
    e.preventDefault();
    window.location = "<%= todos_path %>"
  });

  $('#bbmapp').on('click',function(e){
    e.preventDefault();
    window.location = "<%= marionette_todos_path %>"
  });
});
</script>